### ISSUE TITLE
Output sssom mapping files rather than owl

### ISSUE THREAD

**Issue by matentzn** [INCATools/boomer#293]
For working with boomer more seemlessly, it would be great if it could output the results as a table:

```
mapping_set_id: https://w3id.org/boomer/s8169763872632786387263
license: https://creativecommons.org/publicdomain/zero/1.0/
curie_map:
  UBERON: http...
  FMA: http...
```
| subject_id | subject_label | predicate_id | object_id | object_label | confidence | mapping_justification |
| ---------- | ---------- | ---------- | ---------- | ---------- | ---------- | ---------- |
| UBERON:123 |  heart | skos:exactMatch | FMA:321 | heart | 0.9 | semapv:UnspecifiedMatching | 
| UBERON:123 |  soul | skos:exactMatch | FMA:321 | human soul | 0.9 | semapv:UnspecifiedMatching |
